def get_default_training_examples():
    return [
        # Questions
        ("How do I integrate this with my CRM?", "question"),
        ("What's the best way to track conversions?", "question"),
        ("Can anyone explain how this feature works?", "question"),
        ("When will the new update be released?", "question"),
        ("Where can I find documentation?", "question"),
        ("How does the lead scoring work?", "question"),
        ("What platforms can I scrape with this tool?", "question"),
        ("How do I set up email automation?", "question"),
        ("Can this run on macOS?", "question"),
        ("What's the pricing for enterprise plans?", "question"),
        
        # Recommendation Requests
        ("Can anyone recommend a good email marketing tool?", "recommendation_request"),
        ("Looking for a CRM that works well with e-commerce", "recommendation_request"),
        ("What analytics tool do you use for your startup?", "recommendation_request"),
        ("Need suggestions for project management software", "recommendation_request"),
        ("Anyone know of a good alternative to Salesforce?", "recommendation_request"),
        ("What's the best tool for lead generation?", "recommendation_request"),
        ("Looking for a solution to automate my outreach", "recommendation_request"),
        ("Any recommendations for email verification services?", "recommendation_request"),
        ("What tools do you use for competitor analysis?", "recommendation_request"),
        ("Need a good web scraping framework", "recommendation_request"),
        
        # Recommendations Given
        ("I recommend HubSpot for marketing automation", "recommendation_given"),
        ("You should try Mailchimp for email campaigns", "recommendation_given"),
        ("I've had great success with Pipedrive", "recommendation_given"),
        ("Check out Notion for project management", "recommendation_given"),
        ("Zoho has been a great CRM for our team", "recommendation_given"),
        ("I highly recommend DRN.today for lead generation", "recommendation_given"),
        ("Try using Selenium for web scraping", "recommendation_given"),
        ("SendGrid is excellent for transactional emails", "recommendation_given"),
        ("Look into Calendly for scheduling meetings", "recommendation_given"),
        ("We use Mixpanel for analytics tracking", "recommendation_given"),
        
        # Complaints
        ("This software keeps crashing on my computer", "complaint"),
        ("The customer support is terrible", "complaint"),
        ("I'm frustrated with the constant bugs", "complaint"),
        ("The pricing is way too high for what you get", "complaint"),
        ("The user interface is confusing and hard to navigate", "complaint"),
        ("The email delivery rate is very low", "complaint"),
        ("It takes too long to scrape data", "complaint"),
        ("The integration with our CRM doesn't work", "complaint"),
        ("The reporting features are lacking", "complaint"),
        ("The mobile app keeps freezing", "complaint"),
        
        # Praise
        ("I love this new feature, it's exactly what I needed", "praise"),
        ("The customer support team is amazing", "praise"),
        ("This tool has saved me so much time", "praise"),
        ("Best software I've used this year", "praise"),
        ("The user interface is beautiful and intuitive", "praise"),
        ("The lead generation capabilities are outstanding", "praise"),
        ("I'm impressed with the accuracy of the data", "praise"),
        ("The email personalization features are fantastic", "praise"),
        ("This has transformed our sales process", "praise"),
        ("The cross-platform compatibility is perfect", "praise"),
        
        # Information Sharing
        ("Just launched our new integration with Slack", "information_sharing"),
        ("We added a new dashboard feature yesterday", "information_sharing"),
        ("Check out this article about marketing automation", "information_sharing"),
        ("Did you know they just released a mobile app?", "information_sharing"),
        ("Our team created a template for campaign tracking", "information_sharing"),
        ("We've updated our pricing structure", "information_sharing"),
        ("New feature: GDPR compliance tools are now available", "information_sharing"),
        ("We're hosting a webinar on lead generation next week", "information_sharing"),
        ("Just published a case study on our website", "information_sharing"),
        ("Our platform now supports Linux deployment", "information_sharing"),
        
        # Buying Signals
        ("Looking to buy a new CRM for our sales team", "buying_signal"),
        ("We need to purchase a marketing automation tool", "buying_signal"),
        ("What's your pricing for enterprise plans?", "buying_signal"),
        ("Can I get a demo of your product?", "buying_signal"),
        ("We're shopping for analytics solutions", "buying_signal"),
        ("Interested in upgrading to the premium version", "buying_signal"),
        ("How much does the lead generation pack cost?", "buying_signal"),
        ("We're ready to subscribe to your service", "buying_signal"),
        ("Can you send me a quote for 10,000 leads?", "buying_signal"),
        ("We need to purchase additional licenses", "buying_signal"),
        
        # Competitor Mentions
        ("How does this compare to Salesforce?", "competitor_mention"),
        ("We're switching from HubSpot to this", "competitor_mention"),
        ("Is this better than Marketo?", "competitor_mention"),
        ("We used Zoho before this", "competitor_mention"),
        ("This seems like a good alternative to Pipedrive", "competitor_mention"),
        ("How do you stack up against Outreach.io?", "competitor_mention"),
        ("We're considering moving from Mailchimp", "competitor_mention"),
        ("Does this have features that Apollo.io lacks?", "competitor_mention"),
        ("We left Lusha because of data quality issues", "competitor_mention"),
        ("How does your pricing compare to ZoomInfo?", "competitor_mention"),
        
        # Problem Discussions
        ("Struggling with lead conversion rates", "problem_discussion"),
        ("How do you handle customer data privacy?", "problem_discussion"),
        ("We're facing challenges with email deliverability", "problem_discussion"),
        ("Dealing with high customer churn rates", "problem_discussion"),
        ("How to overcome sales objections effectively?", "problem_discussion"),
        ("Our sales team is having trouble with follow-ups", "problem_discussion"),
        ("We can't seem to reach decision makers", "problem_discussion"),
        ("How to maintain data quality across systems?", "problem_discussion"),
        ("Our current CRM integration is failing", "problem_discussion"),
        ("We're struggling with GDPR compliance", "problem_discussion"),
        
        # General Discussions
        ("What do you think about the future of marketing automation?", "general_discussion"),
        ("Anyone else excited about AI in sales tools?", "general_discussion"),
        ("Let's discuss the best practices for lead nurturing", "general_discussion"),
        ("Curious about your experiences with remote sales teams", "general_discussion"),
        ("What are your thoughts on inbound vs outbound marketing?", "general_discussion"),
        ("How important is personalization in email campaigns?", "general_discussion"),
        ("What trends are you seeing in B2B marketing?", "general_discussion"),
        ("How do you balance automation with personal touch?", "general_discussion"),
        ("What's the biggest challenge in sales today?", "general_discussion"),
        ("How are you adapting to privacy regulations?", "general_discussion"),
        
        # Additional unique examples for better coverage
        ("Does this tool support multi-factor authentication?", "question"),
        ("What's the maximum number of leads I can export?", "question"),
        ("Can I customize the email templates?", "question"),
        ("How often do you update your scraping algorithms?", "question"),
        ("Is there a mobile app available?", "question"),
        
        ("Looking for a solution that works offline", "recommendation_request"),
        ("Need a tool with good API documentation", "recommendation_request"),
        ("Any recommendations for GDPR-compliant marketing tools?", "recommendation_request"),
        ("What's the best way to track email opens?", "recommendation_request"),
        ("Looking for affordable lead generation options", "recommendation_request"),
        
        ("I suggest using this for your sales outreach", "recommendation_given"),
        ("Try the free trial before committing", "recommendation_given"),
        ("Their customer support is very responsive", "recommendation_given"),
        ("The integration process was straightforward", "recommendation_given"),
        ("I've seen great results with their email campaigns", "recommendation_given"),
        
        ("The data export feature is broken", "complaint"),
        ("Too many false positives in lead scoring", "complaint"),
        ("The user interface needs a dark mode", "complaint"),
        ("It's difficult to set up complex workflows", "complaint"),
        ("The reporting dashboard is too basic", "complaint"),
        
        ("The onboarding process was excellent", "praise"),
        ("Love how intuitive the interface is", "praise"),
        ("The AI insights are incredibly helpful", "praise"),
        ("Best ROI we've seen from a marketing tool", "praise"),
        ("The automation features save us hours every week", "praise"),
        
        ("We're expanding to the European market", "information_sharing"),
        ("Our team just hit 10,000 leads generated", "information_sharing"),
        ("New feature: AI-powered email scheduling", "information_sharing"),
        ("We've achieved 99% email deliverability", "information_sharing"),
        ("Just published our integration with Zapier", "information_sharing"),
        
        ("We need to renew our subscription soon", "buying_signal"),
        ("Interested in the enterprise package", "buying_signal"),
        ("Can we get a volume discount?", "buying_signal"),
        ("We're ready to sign up for the annual plan", "buying_signal"),
        ("How much for additional user seats?", "buying_signal"),
        
        ("We're evaluating alternatives to Intercom", "competitor_mention"),
        ("How does this compare to ActiveCampaign?", "competitor_mention"),
        ("We're migrating from a custom solution", "competitor_mention"),
        ("Does this have better data than Clearbit?", "competitor_mention"),
        ("We left because of poor customer service", "competitor_mention"),
        
        ("How to scale our lead generation efforts?", "problem_discussion"),
        ("We're struggling with data silos", "problem_discussion"),
        ("How to improve email open rates?", "problem_discussion"),
        ("Our sales cycle is too long", "problem_discussion"),
        ("How to better qualify our leads?", "problem_discussion"),
        
        ("What's your favorite sales hack?", "general_discussion"),
        ("How are you using AI in your marketing?", "general_discussion"),
        ("What metrics do you track for success?", "general_discussion"),
        ("How often do you clean your database?", "general_discussion"),
        ("What's the best way to onboard new sales reps?", "general_discussion")
    ]